version: '3'
services:
  component:
    image: node:10-alpine
    environment:
        - TCP_LISTEN_PORT=9375
    ports:
      - "9375:9375"
    command: node --experimental-modules /bundler/serve.mjs
    working_dir: /bmpjs
    volumes:
      # PLAYGROUND
      - ./bmpjs/playground:/bmpjs/playground
      - ./bmpjs/project:/bmpjs/project
      # CORE
      - ./bmpjs/bmp-core:/bmpjs/bmp-core
      # ROUTER
      - ./bmpjs/bmp-router:/bmpjs/bmp-router
      # BUNDLER
      - ./bmpjs/bundler:/bundler:ro

  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      # CORE
      - ./bmpjs/bmp-core/.tmp:/usr/share/nginx/html/bmp-core

      # ROUTER
      - ./bmpjs/bmp-router/.tmp:/usr/share/nginx/html/bmp-router

      # PLAYGROUND
      - ./bmpjs/playground/.tmp:/usr/share/nginx/html/playground
      - ./bmpjs/playground/bmp_modules:/usr/share/nginx/html/playground/bmp_modules

      # PROJECT
      - ./bmpjs/project/.tmp:/usr/share/nginx/html/project
      - ./bmpjs/project/bmp_modules:/usr/share/nginx/html/project/bmp_modules

