version: 2
jobs:

  test:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/boomfunc/base

    steps:
      - checkout
      - run: ./.ci/scripts/test.sh


  build:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/boomfunc/base

    steps:
      - checkout
      - run: ./.ci/scripts/build.sh
      - persist_to_workspace:
          root: /go/bin
          paths:
            - "*"

  deploy:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/boomfunc/base

    steps:
      - checkout
      - run: go get github.com/tcnksm/ghr
      - attach_workspace:
          at: /tmp/workspace
      - run: |
          ghr -t $GITHUB_TOKEN \
              -u $CIRCLE_PROJECT_USERNAME \
              -r $CIRCLE_PROJECT_REPONAME \
              --prerelease --delete \
              $CIRCLE_TAG /tmp/workspace

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - test:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          requires:
            - test
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          requires:
            - build
