version: "3"
services:
  ssrbmp:
    image: node:10.9-alpine
    restart: always
    volumes:
      - .:/ssr
    working_dir: /ssr
    # entrypoint: node
    command: tail -f /dev/null

  ms:
    build:
      context: .
    environment:
      - BMP_DEBUG_MODE=true
      - BMP_CONFIG=./example.yml
    ports:
        - "8081:8080"
    # logging: *logging
