version: "3"
services:
    ssrbmp:
        image: node:10.9-alpine
        restart: always
        volumes:
            - .:/ssr
        working_dir: /ssr
        # entrypoint: node
        command: tail -f /dev/null
