version: 2
jobs:

  ssr-test:
    docker:
      - image: node:10
    steps:
      - checkout
      - run:
          name: Build core
          working_directory: ./bmpjs/ssr
          command: |
            npm install
            npm test

  build-core:
    docker:
      - image: node:10
    steps:
      - checkout
      - run:
          name: Build core
          working_directory: ./bmpjs/core
          command: |
            npm install
            node --experimental-modules ./install.mjs
            node --experimental-modules ./build.mjs
            rm -rf node_modules
      - persist_to_workspace:
          root: ./bmpjs
          paths:
            - core/*

  build-router:
    docker:
      - image: node:10
    steps:
      - checkout
      - run:
          name: Build router
          working_directory: ./bmpjs/router
          command: |
            npm install
            node --experimental-modules ./install.mjs
            node --experimental-modules ./build.mjs
            rm -rf node_modules
      - persist_to_workspace:
          root: ./bmpjs
          paths:
            - router/*

  deploy:
    docker:
      - image: atlassian/pipelines-awscli

    steps:
      - checkout
      - attach_workspace:
          at: ./bmpjs

      - run:
          working_directory: ./bmpjs/router
          command: tar -zcv . | aws s3 cp - "s3://io-boomfunc-root/bmpjs/router.tar.gz" --acl private --cache-control 'public, max-age=0, s-maxage=31536000, must-revalidate'
      - run:
          working_directory: ./bmpjs/core
          command: tar -zcv . | aws s3 cp - "s3://io-boomfunc-root/bmpjs/core.tar.gz" --acl private --cache-control 'public, max-age=0, s-maxage=31536000, must-revalidate'
      - run:
          working_directory: ./bmpjs/bundler
          command: tar -zcv . | aws s3 cp - "s3://io-boomfunc-root/bmpjs/bundler.tar.gz" --acl private --cache-control 'public, max-age=0, s-maxage=31536000, must-revalidate'
      - run: aws cloudfront create-invalidation --distribution-id E39RHHF1ID06TC --paths "/*"

workflows:
  version: 2
  deploy:
    jobs:
      - ssr-test
      - build-core
      - build-router
      - deploy:
          requires:
            - build-core
            - build-router

