version: 2
jobs:

  deploy:
    docker:
      - image: atlassian/pipelines-awscli
    steps:
      - checkout
      - run:
          name: Deploy
          working_directory: ./bmpjs
          command: |
            tar -zcv ./bundler | aws s3 cp - "s3://io-boomfunc-root/bmpjs/bundler.tar.gz" --acl private --cache-control 'public, max-age=0, s-maxage=31536000, must-revalidate'
            tar -zcv ./bmp-router | aws s3 cp - "s3://io-boomfunc-root/bmpjs/bmp-router.tar.gz" --acl private --cache-control 'public, max-age=0, s-maxage=31536000, must-revalidate'
            tar -zcv ./bmp-core | aws s3 cp - "s3://io-boomfunc-root/bmpjs/bmp-core.tar.gz" --acl private --cache-control 'public, max-age=0, s-maxage=31536000, must-revalidate'
            aws cloudfront create-invalidation --distribution-id E39RHHF1ID06TC --paths "/*"

workflows:
  version: 2

  deploy-bundler:
    jobs:
      - deploy
