version: '3'
services:
  component:
    build:
      context: .
    environment:
        - TCP_LISTEN_PORT=9375
        - NODE_PATH=/usr/lib/node_modules
    ports:
      - "9375:9375"
    working_dir: /bmpjs
    volumes:
      - ./:/bmpjs

  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      # CORE
      - ./bmp-core:/usr/share/nginx/html/bmp-core

      # ROUTER
      - ./bmp-router:/usr/share/nginx/html/bmp-router

      # PROJECT
      - ./jetsmarter/.tmp:/usr/share/nginx/html/jetsmarter
      - ./jetsmarter/bmp_modules:/usr/share/nginx/html/jetsmarter/bmp_modules

