version: '3'
services:
  component:
    build:
      context: .
    environment:
        - TCP_LISTEN_PORT=9375
        - NODE_PATH=/usr/lib/node_modules
    ports:
      - "9375:9375"
    working_dir: /bmpjs
    volumes:
      - ./:/bmpjs

  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      # CORE
      - ./core:/usr/share/nginx/html/core

      # ROUTER
      - ./router:/usr/share/nginx/html/router

      # PROJECT
      - ./jetsmarter/.tmp:/usr/share/nginx/html/jetsmarter
      - ./jetsmarter/bmp_modules:/usr/share/nginx/html/jetsmarter/bmp_modules

  ssr:
    image: node:10.9-alpine
    restart: always
    volumes:
      - .:/ssr
    working_dir: /ssr
    # entrypoint: node
    command: tail -f /dev/null

  ms:
    build:
      context: ./serverside-render
    environment:
      - BMP_DEBUG_MODE=true
      - BMP_CONFIG=./example.yml
    ports:
        - "8081:8080"
